/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\man.glb 
Author: dazqu1991 (https://sketchfab.com/dazqu1991)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/walk-man-ca5429ebe74944c7949f05270e99b359
Title: walk man
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'
import { SkeletonUtils } from 'three-stdlib'
interface ModelProps {
  [key: string]: unknown;
}

function angleToRadians(angle: number): number {
  return angle * (Math.PI / 180);
}
export function WalkMan(props: ModelProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/man/man.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} scale={[0.5, 0.5, 0.5]} rotation={[0, angleToRadians(90), 0]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.999}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sketchfab_model_0" rotation={[-Math.PI / 2, 0, 0]} scale={1.826}>
                <group name="root_1">
                  <group name="GLTF_SceneRootNode_2" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Tourist_Man_53_3" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                      <group name="GLTF_created_0_4">
                        <group name="GLTF_created_0">
                          <primitive object={nodes.GLTF_created_0_rootJoint} />
                          <skinnedMesh name="Object_65" geometry={(nodes.Object_65 as THREE.SkinnedMesh).geometry} material={materials['Material.001']} skeleton={(nodes.Object_65 as THREE.SkinnedMesh).skeleton} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/man/man.glb')
